### ISSUE TITLE
Can't change the ParallaxComponent size attribut

### ISSUE THREAD

**Issue by Pierre-Monier** [flame-engine/flame#799] opened 2021-05-18 19:32 UTC
# Current bug behaviour
I show this issue on the discord channel and somebody said that it seems like a bug, so I'm reporting this issue.

I can't change the size off the ParallaxComponent. Event if I specify a size for it, it always has the full screen device size. 

I use something like this 
```dart
    final image = await loadParallaxImage('image.png',
        fill: LayerFill.width, alignment: Alignment.bottomLeft);

    final layer = ParallaxLayer(image, velocityMultiplier: Vector2(1.0, 1.0));

    sprite = ParallaxComponent.fromParallax(
        Parallax([layer], Vector2(10, 10), baseVelocity: Vector2(200.0, 0.0)),
        position: Vector2(0, 0),
        size: Vector2(10, 10));
```

As you can see I specified a size of `Vector2(10,10)` in the Parallax object and in the `fromParallax` method. But none of this are changing anything.

I also try to change the fill param in the loadParallaxImage, but it doesn't change a thing too.

In any case when I do `print(sprite.size.toString());` it always gives me `[411.42857142857144,875.4285714285714]` (my phone size)

# Expected behaviour

I want to be able to change the size of the ParallaxComponent

# Steps to reproduce

I use this code
```dart
    final image = await loadParallaxImage('image.png',
        fill: LayerFill.width, alignment: Alignment.bottomLeft);

    final layer = ParallaxLayer(image, velocityMultiplier: Vector2(1.0, 1.0));

    sprite = ParallaxComponent.fromParallax(
        Parallax([layer], Vector2(10, 10), baseVelocity: Vector2(200.0, 0.0)),
        position: Vector2(0, 0),
        size: Vector2(10, 10));

    print(sprite.size.toString());
```
# Flutter doctor output

```
[✓] Flutter (Channel beta, 2.1.0-12.2.pre, on macOS 11.2 20D64 darwin-x64,
    locale fr-FR)
    • Flutter version 2.1.0-12.2.pre at /Users/Stardev/flutter
    • Framework revision 5bedb7b1d5 (il y a 9 semaines), 2021-03-17 17:06:30
      -0700
    • Engine revision 711ab3fda0
    • Dart version 2.13.0 (build 2.13.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version
    30.0.3)
    • Android SDK at /Users/stardev/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/stardev/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/stardev/Library/Android/sdk
    • Java binary at:
      /Library/Java/JavaVirtualMachines/adoptopenjdk-8.jdk/Contents/Home/bin
      /java
    • Java version OpenJDK Runtime Environment (AdoptOpenJDK)(build
      1.8.0_292-b10)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for
      iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch
        /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[!] Android Studio (not installed)
    • Android Studio not found; download from
      https://developer.android.com/studio/index.html
      (or visit
      https://flutter.dev/docs/get-started/install/macos#android-setup for
      detailed instructions).

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • Pixel 4a 5G (mobile) • 0B111JECB04556 • android-arm64  • Android 11
      (API 30)
    • Chrome (web)         • chrome         • web-javascript • Google Chrome
      90.0.4430.212

! Doctor found issues in 2 categories.
```

# More environment information
* Flame version: ^1.0.0-rc5
* Platform affected: android
* Platform version affected: android 11

**Comment by spydon** [comment] 2021-05-19 06:56
I don't know if it was you that reported this on discord, but this is definitely a bug.
The problem is on `onGameResize` on the `ParallaxComponent` where it overwrites the set user value with the full screen value, so meanwhile until we fix it you can simply override `onGameResize` and it should work, but I haven't testted it so please report back if you do test it.

**Comment by luanpotter** [comment] 2021-06-01 01:51
Closing as the PR was merged

**Closed by luanpotter** 2021-06-01 01:51 UTC
Labels: bug
