### ISSUE TITLE
Maintaining Consistent Border Thickness Across Different Drawing Scales in NineTile

### ISSUE THREAD

**Issue by shingo-nakanishi** [flame-engine/flame#3422] opened 2024-12-22 01:19 UTC
### What happened?

I am trying to render borders with a consistent thickness regardless of the size of the drawing area.

I have prepared the following image:

- Image
  - Corners: 6px
  - Image size: 18px x 18px

![nine-tile](https://github.com/user-attachments/assets/267a8890-3a32-4b44-9986-4bc616a8d621)

When I change the scale by tapping, the border size becomes thicker according to the scale.
I expected the thickness to remain fixed at the value specified in destTileSize, but it seems that destTileSize is not functioning as expected (changing the value has no effect, regardless of the scale).

### What do you expect?

The pixels are drawn according to the destTileSize.

- While scaling up or down based on the scale seems acceptable, at the very least, the set value should be reflected.
- In this example, something drawn at 6px is expected to be rendered at 60px, so the border on screen should appear 10 times thicker than the image.

### How can we reproduce this?

Code
```
import 'package:flame/components.dart';
import 'package:flame/game.dart';
import 'package:flame/input.dart';

class NineTileBoxExample extends FlameGame with TapDetector, DoubleTapDetector {
  late NineTileBoxComponent nineTileBoxComponent;

  @override
  Future<void> onLoad() async {
    final sprite = Sprite(await images.load('nine-tile.png'));
    final boxSize = Vector2.all(500);
    final nineTileBox = NineTileBox(
      sprite,
      tileSize: 6,
      destTileSize: 60, // I changed various values, but nothing has been reflected even before changing the scale with a tap.
    );
    add(
      nineTileBoxComponent = NineTileBoxComponent(
        nineTileBox: nineTileBox,
        position: size / 2,
        size: boxSize,
        anchor: Anchor.center,
      ),
    );
  }

  @override
  void onTap() {
    nineTileBoxComponent.scale.scale(1.2);
  }

  @override
  void onDoubleTap() {
    nineTileBoxComponent.scale.scale(0.8);
  }
}
```

Reference: https://github.com/flame-engine/flame/blob/main/examples/lib/stories/rendering/nine_tile_box_example.dart

**The actual behavior: (the corners seem to be drawn at 12 x 12.)**

![Screenshot 2024-12-22 at 10 41 18](https://github.com/user-attachments/assets/9faa7033-2d84-444f-acf0-0e292238bf4a)

### Execute in a terminal and put output into the code block below

Output of: flutter doctor -v

### Affected platforms

macOS, Web

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment] 2024-12-22 19:34
You should change the size, not the scale to not make the borders thicker. This is by design so I'll close this.

**Closed by spydon** 2024-12-22 19:34 UTC
Labels: bug

**Comment by shingo-nakanishi** [comment] 2024-12-22 23:56
@spydon 

The size is just an example, and as mentioned, changing the value of destTileSize doesn’t make any difference in the first place.

For instance, in the example above, destTileSize is set to 60, but it is not being rendered at 60px.

I might be misunderstanding how to use destTileSize in the first place, so could you explain a simple way to draw lines thicker than those in the pixel image?

**Comment by shingo-nakanishi** [comment] 2024-12-23 00:02
What I want to achieve is to "draw lines with the intended thickness, regardless of the size." However, the issue seems to be either that "destTileSize doesn’t appear to be functioning properly" or "I might be misunderstanding how to use destTileSize."

**Comment by spydon** [comment] 2024-12-23 07:52
It's the `size` of the component that you should change if you're using a component, not the `destTileSize`.  I guess this should be clarified in the docs.

**Comment by shingo-nakanishi** [comment] 2024-12-24 00:50
I'm still not entirely sure, but I tried doing it like the code below (I just wanted to change the border, though):

```
@override
  Future<void> onLoad() async {
    final sprite = Sprite(await images.load('nine-tile.png'));
    final boxSize = Vector2.all(33); // 👈👈 Divided by 3
    final nineTileBox = NineTileBox(
      sprite,
    );
    add(
      nineTileBoxComponent = NineTileBoxComponent(
        nineTileBox: nineTileBox,
        position: size / 2,
        size: boxSize,
        anchor: Anchor.center,
        scale: Vector2(3, 3), // 👈👈 3x scaling
      ),
    );
  }
```

![Screenshot 2024-12-24 at 9 49 41](https://github.com/user-attachments/assets/7d113f93-db4f-48b8-b8e9-ad220a56baaa)

**Comment by spydon** [comment] 2024-12-24 08:26
You are still setting the scale the scale will always zoom, you to set the size to `size * 3` if you want the border to have the same thickness.
