### ISSUE TITLE
"FlameAudio.play('file_name.wav');" in windows 10, 10 an error occurs. 

### ISSUE THREAD

**Issue by izanled** [flame-engine/flame#1390] opened 2022-02-21 04:41 UTC
# Current bug behaviour
Sound does not play in Windows environment. 

# Expected behaviour
normal sound play 

# Steps to reproduce
void jump() {
    FlameAudio.play('wing.wav');
    status = BirdStatus.flying;
    _counter = 0;
    ground.angle = 0;
  }

# Flutter doctor output
[√] Flutter (Channel stable, 2.10.2, on Microsoft Windows [Version 10.0.22000.493], locale ko-KR)
    • Flutter version 2.10.2 at C:\Users\MiDAS\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (2 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
    • Android SDK at C:\Users\MiDAS\AppData\Local\Android\sdk
    • Platform android-32, build-tools 33.0.0-rc1
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.11+9-b60-7590822)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
    • Visual Studio at C:\Program Files\Microsoft Visual Studio\2022\Community
    • Visual Studio Community 2022 version 17.1.32210.238
    • Windows 10 SDK version 10.0.19041.0

[√] Android Studio (version 2021.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.64.2)
    • VS Code at C:\Users\MiDAS\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.34.0

[√] Connected device (4 available)
    • SM P200 (mobile)  • R54M800R9VL • android-arm64  • Android 11 (API 30)
    • Windows (desktop) • windows     • windows-x64    • Microsoft Windows [Version 10.0.22000.493]
    • Chrome (web)      • chrome      • web-javascript • Google Chrome 98.0.4758.82
    • Edge (web)        • edge        • web-javascript • Microsoft Edge 98.0.1108.56

[√] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

# More environment information

# Log information
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method play on channel xyz.luan/audioplayers)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:175)
<asynchronous suspension>
#1      AudioPlayer.invokeMethod (package:audioplayers/src/audioplayer.dart:151)
<asynchronous suspension>
#2      AudioPlayer.play (package:audioplayers/src/audioplayer.dart:173)
<asynchronous suspension>
#3      AudioCache.play (package:audioplayers/src/audio_cache.dart:164)
<asynchronous suspension>

**Comment by erickzanardo** [comment] 2022-03-25 19:32
Windows is not yet supported on Audioplayers. Something which may change in the near future: https://github.com/bluefireteam/audioplayers/pull/1068

Closing since this platform isn't supported yet and is not a bug on flame audio

**Closed by erickzanardo** 2022-03-25 19:32 UTC
Labels: bug
