### ISSUE TITLE
Anti aliasing issue

### ISSUE THREAD

**Issue by Harmonic999** [flame-engine/flame#113] opened 2019-06-25 16:02 UTC
When rotating sprite component 'edges' appear like you can see on the screenshots below. Are there any solutions to smooth them? 

1. Card without rotation.

![1](https://user-images.githubusercontent.com/39963047/60113245-05c34b80-977a-11e9-896b-268ee3bd3454.png)

2. Card with rotation.

![2](https://user-images.githubusercontent.com/39963047/60113288-1b387580-977a-11e9-99f4-c7858d7e8c46.png)

**Comment by erickzanardo** [comment] 2019-06-25 16:09
Hey @Harmonic999 

Are the cards images big enough for the resolution of the game? Even the seven of hearts on the first image seems to be a little "crisp".

Another thing that you can test, `drawImage` from the canvas receives a Paint, which has an antiAlias property, you could try changing it to see if there is any difference.

https://api.flutter.dev/flutter/dart-ui/Canvas/drawImage.html
https://api.flutter.dev/flutter/dart-ui/Paint/isAntiAlias.html

**Comment by Harmonic999** [comment] 2019-06-26 12:26
Thank you for your quick response @erickzanardo. I have just tried using drawImage but unfortunetly it doesn't give any promising results.

resolution of the game is 360x592.
card's original size is 180x240 pixels.

I tried using high quality assets and still result is the same when trying to rotate something..

```
paint = Paint()..isAntiAlias = true;

void render(Canvas canvas) {
    background.render(canvas, screenWidth, screenHeight);
    canvas.rotate(0.12);
    canvas.drawImageRect(GameResources.card, src, dst, paint);
  }
```

![3](https://user-images.githubusercontent.com/39963047/60178856-0bc23680-9825-11e9-8804-8e9b455eb659.png)

**Comment by erickzanardo** [comment] 2019-06-26 13:11
> resolution of the game is 360x592.
Just be aware that this is not in pixels, that is usually logical pixels, so a 180x240pixels image is kind small.

Have you tried turning the isAntiAlias to `false`? it is `true` by default, sometimes these anti alias functions can mess up with things, maybe it is worth a try.

I will try to make some tests with rotating images and will try to report back here.

Also if possible, can you share the card image with us? So I can test with the asset that is causing the problem.

Thanks

**Comment by Harmonic999** [comment] 2019-06-26 13:42
> Have you tried turning the isAntiAlias to false? it is true by default, sometimes these anti alias functions can mess up with things, maybe it is worth a try.

Yes i have tried, but it looks like it doesn't affect anything.

> Also if possible, can you share the card image with us? So I can test with the asset that is causing the problem.

Sure, here is the card. 

![card_deselected](https://user-images.githubusercontent.com/39963047/60184119-264ddd00-9830-11e9-85e8-0d2842cd2570.png)

I will also try to experiment a little with rotations.

**Comment by dd-celerity** [comment] 2019-06-26 14:42
What device are you testing this on?
The core of the Sprite render method uses drawImageRect, which relies on the Paint's FilterQuality attribute. AntiAlias isn't going to do much.

The default FilterQuality value is Low, which is standard bilinear filter and should look fine.  Here's your card rendered on my iPhoneSE:

![card_high](https://user-images.githubusercontent.com/32303954/60188150-d0ac0d00-97fc-11e9-90b4-ac2fff34f60d.png)
![card_none](https://user-images.githubusercontent.com/32303954/60188158-d43f9400-97fc-11e9-9d22-7f9f5568a664.png)

The first one has FilterQuality set to Low (default), the second one has it set to None.  My guess is that this is a GPU issue with your device and it's not doing any image filtering. Perhaps you're on a simulator that does software rendering? Or a really low-end device?

You can manually set the FilterQuality for a sprite with this code, if you want to give that a try:
`mySprite.paint.filterQuality = FilterQuality.low; ` or `FilterQuality.high;`

**Comment by Harmonic999** [comment] 2019-06-26 14:47
@dd-celerity Wow, thanks, setting filter quality really helped, now everything renders fantastic

**Comment by ddonze** [comment] 2019-06-26 14:50
You're welcome!  Glad it helped.
(dd-celerity is my work account. I didnt realize i was logged in with that account when I posted that response.  Oop!)

**Comment by erickzanardo** [comment] 2019-06-29 16:22
Thanks for the help @ddonze closing this since the problem is solved.

**Closed by erickzanardo** 2019-06-29 16:22 UTC
