### ISSUE TITLE
Interactive docs: `RotateEffect`

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1950] opened 2022-09-29 19:19 UTC
# Interactive doc for the `RotateEffect`s

The two `RotateEffect`s should have small examples that show how the effect is applied and how it works. This could for example be just clicking somewhere in the game and rotating a geometrical shape to the position where the reader clicked.

https://docs.flame-engine.org/1.3.0/flame/effects.html#rotateeffect-by
https://docs.flame-engine.org/1.3.0/flame/effects.html#rotateeffect-to

# What are interactive docs?

On our documentation site has the possibility to run inline interactive examples and we would like every visual feature to have a **small**, pretty and easily understandable example attached to it. Some current examples are the [router](https://docs.flame-engine.org/1.3.0/flame/router.html) and the [decorators](https://docs.flame-engine.org/1.3.0/flame/rendering/decorators.html).
Some inspiration can also be found on our [examples page](https://examples.flame-engine.org) where we have examples for most features.

# Good to know

Make sure that you comment on the issue that you will be working on this before starting to program.

To set up the Flame environment you need to follow the instructions in our [contributing.md](https://github.com/flame-engine/flame/blob/main/CONTRIBUTING.md#environment-setup) doc, if you have any problems setting up your environment (or other issues of course) feel free to ask for help in the Flame channel on our [Discord server](https://discord.com/invite/pxrBmy4).

Since this is a documentation change, you need to be able to build the docs. Instructions for building the documentation site locally can be found here: https://docs.flame-engine.org/main/development/documentation.html#building-documentation-locally

Make sure to include a video of the example when you upload the PR so that it will be easier for us to review it. (You can attach videos directly in the PR, so no need to upload them somewhere else)

**Happy hacking!**

**Comment by viveknshah** [comment] 2022-10-01 06:58
I'd be interested in contributing here.

**Comment by spydon** [comment] 2022-10-01 09:05
> I'd be interested in contributing here. 

Super! I've assigned you to the issue, remember to join our Discord server if you have any questions etc. :)

**Comment by munsterlander** [comment] 2022-10-02 22:29
I will gladly help out if needed.

**Comment by viveknshah** [comment] 2022-10-03 07:34
Almost done - getting a 404 for the animated example when I run the docs on  localhost though so figuring that out

**Comment by munsterlander** [comment] 2022-10-05 02:19
Did you get it solved?  I build the docs a ton, so happy to help you out so you can get your PR submitted.

**Comment by viveknshah** [comment] 2022-10-05 09:02
Have unassigned myself. I broken my head too long on the local build. Tried to start from scratch and can't get that to be built also let alone after my changes. Feel free to go ahead @munsterlander

**Comment by viveknshah** [comment] 2022-10-05 09:03
![image](https://user-images.githubusercontent.com/7208041/194023139-7acc8d46-b6df-494f-a74f-9205a62a2e50.png)

The build errors I keep seeing even when I start afresh from a git pull

**Comment by munsterlander** [comment] 2022-10-05 09:04
@spydon can this be assigned to me?

**Comment by munsterlander** [comment] 2022-10-05 09:04
> ![image](https://user-images.githubusercontent.com/7208041/194023139-7acc8d46-b6df-494f-a74f-9205a62a2e50.png)
> 
> The build errors I keep seeing even when I start afresh from a git pull

@spydon @st-pasha It's not just me!

**Comment by ufrshubham** [comment] 2022-10-05 09:27
@viveknshah @munsterlander it might be because you guys have not run `melos bootstrap` in your local repo. I can reproduce this problem if I clean melos and just try to build that `doc/flame/examples`.

**Comment by viveknshah** [comment] 2022-10-05 09:39
> @viveknshah @munsterlander it might be because you guys have not run `melos bootstrap` in your local repo. I can reproduce this problem if I clean melos and just try to build that `doc/flame/examples`.

That fixed the local build for me. 

@munsterlander I still see the following though when I try running locally for all animations- the same issue I saw when trying to test my changes. 

![image](https://user-images.githubusercontent.com/7208041/194030455-39caafeb-e4c0-4e0f-bec8-4fc9d6ee60ca.png)

**Comment by spydon** [comment] 2022-10-05 09:42
> @munsterlander I still see the following though when I try running locally for all animations- the same issue I saw when trying to test my changes. 
> 
> ![image](https://user-images.githubusercontent.com/7208041/194030455-39caafeb-e4c0-4e0f-bec8-4fc9d6ee60ca.png)
> 

Hmm, I see those 404s now too... Seems like the examples aren't built properly.

**Comment by munsterlander** [comment] 2022-10-05 09:43
Everything works for me....well melos bootstrap is still running, so maybe after that, it no longer will.

**Closed** 2022-10-06 14:59 UTC
Labels: enhancement, good first issue, documentation, hacktoberfest, interactive docs
