### ISSUE TITLE
Background music coming out of earpiece speaker only on iOS (Flame audio)

### ISSUE THREAD

**Issue by uristrimber** [flame-engine/flame#1880] opened 2022-08-31 18:10 UTC
# Current bug behaviour

Background music coming out of earpiece speaker only on iOS
# Expected behaviour

The sound should come out of the main speaker also
# Steps to reproduce

Initialize bgm music, play any file.

# More environment information

Create a list of more environment information, like:
* Flame version: 1.3.0
* Platform affected: ios
* Platform version affected: ios 15

**Comment by spydon** [comment] 2022-08-31 20:13
Duplicate of #1194

**Closed** 2022-08-31 20:15 UTC
Labels: bug

**Comment by uristrimber** [comment] 2022-08-31 20:21
@spydon do you want me to pr the fix to flame_audio? I just came to the same solution as on https://github.com/bluefireteam/audioplayers/issues/1194

**Comment by spydon** [comment] 2022-08-31 23:33
> @spydon do you want me to pr the fix to flame_audio? I just came to the same solution as on https://github.com/bluefireteam/audioplayers/issues/1194

The PR should go to audioplayers (we maintain that too) if you have a good fix, flame_audio is just a thin wrapper.
