### ISSUE TITLE
Release app bugs

### ISSUE THREAD

**Issue by holyxiaoxin** [flame-engine/flame#146] opened 2019-08-27 19:19 UTC
When in debug mode, the app is rendering the dimensions properly, but when I install the app from the apk generated in release mode from `flutter build apk`, there is about 50% chance that I'm getting some weird size issues where the whole screen is blackout, with some misplaced widgets. I'm already using `await Flame.util.initialDimensions()`. I'm not sure what's causing the sizing race conditions

```dart
class MyGame extends BaseGame {
  MyGame() {
    initialize();
  }

  void initialize() async {
      resize(await Flame.util.initialDimensions());
      add(...);
      ....
  }
}
```

I'm also facing some issues with text rendering's color. I tried different colors like black and pink, but the color seem to appear correctly only in debugging mode. When in release mode, it's always showing white. `TextConfig(color: Color(0xff000000), fontSize: 20.0, fontFamily: 'Arial', textAlign: TextAlign.left);` I also tried `color: BasicPalette.black.color`.

There's a small annoyance about the Audio library, where the debug logs seem to be always streaming in even when I've already called `Flame.audio.disableLog();`. The first stream of logs tracks the position during `Flame.audio.loadAll(['....mp3']);`, and the other stream of logs has some warnings/exceptions that doesn't break the game, by calling `await Flame.audio.loopLongAudio('.....mp3', volume: .25);`. And also, during development, when you make a save/hot reload, a new audio (that's called during initialisation) gets played and stacked on top of the previous one, the only way to stop this is of course but killing the app. Do you need to stop it by adding a `bgm.pause()` during the widget hotreload hook?

**Comment by erickzanardo** [comment] 2019-08-30 13:15
About the size problem there seems to be a problem with Flutter regarding this, we can see some workaround on this issue: https://github.com/flame-engine/flame/issues/81

The font problem, never saw that happening, is this happening on a specific device? Have you tried testing on different devices/emulators?

The log issue, is indeed something annoying, but so far we couldn't do much about it, it is something reported on audiolayers repository as well, there ins't much we can do about it on Flame.

About the hot reload, yeah, when you hot reload, the music keeps playing, I am not aware of hot reload hook, I usually enable sounds/music only when I am testing the game on release mode.

**Comment by holyxiaoxin** [comment] 2019-09-01 15:46
@erickzanardo I tried running `https://github.com/flame-engine/flame/tree/master/doc/examples/text` on flame v0.15.1, android note 9. Still having the same issues.

**Comment by holyxiaoxin** [comment] 2019-09-01 16:33
@erickzanardo seems that the author for https://jap.alekhin.io/create-mobile-game-flutter-flame-beginner-tutorial is having the same issue.

![image](https://user-images.githubusercontent.com/5796213/64079286-617cf880-cd18-11e9-82af-1a2bddaa5cbf.png)

It seems that material's textPainter is not rendering it properly, a current workaround is to render a Text Widget instead. https://jap.alekhin.io/setup-widget-tree-flame-flutter-game

It also seem that the resize(0,0) is called in release mode which makes this library quite unusable. One workaround for fixed orientation screens is to scale the app in BaseGame.render, against a base width and height like 720*1280, and call super.render. With this setup, the children components can just work with a fixed resolution of 720*1280.

**Comment by erickzanardo** [comment] 2019-09-17 22:43
@holyxiaoxin the resize(0,0) bug is a know issue, caused by a weird Flutter behaviour, like I commented before it has a workaround: https://github.com/flame-engine/flame/issues/81, I am going to close this and open an specific issue about the TextPainter.

**Closed by erickzanardo** 2019-09-17 22:43 UTC
Labels: question
