### ISSUE TITLE
dragcallback and tapcallback not working in web browser

### ISSUE THREAD

**Issue by renanyoy** [flame-engine/flame#2692] opened 2023-08-29 07:13 UTC
# Current bug behavior
not events

# Expected behavior
receiving events

# Steps to reproduce
``` 
class LayerComponent extends RectangleComponent
    with DragCallbacks, TapCallbacks {
  final Layer layer;
  LayerComponent({required this.layer})
      : super(
            position: layer.position,
            size: layer.size,
            angle: layer.angle,
            anchor: layer.anchor,
            paint: Paint()
              ..style = PaintingStyle.stroke
              ..strokeWidth = 2
              ..color = const Color(0xFF0000FF));
  @override
  FutureOr<void> onLoad() {}

  void select(bool selected) {
    paint.color = selected ? const Color(0xFF00FF00) : const Color(0xFF0000FF);
  }

  @override
  void onDragStart(DragStartEvent event) {
    super.onDragStart(event);
    Debug.info(event);
  }

  @override
  void onTapDown(TapDownEvent event) {
    Debug.info('onTapDown: ${event.localPosition}');
  }

  @override
  void onLongTapDown(TapDownEvent event) {}
  @override
  void onTapUp(TapUpEvent event) {}
  @override
  void onTapCancel(TapCancelEvent event) {}
}
``` 
# Flutter doctor output
```
[✓] Flutter (Channel stable, 3.13.1, on macOS 13.4.1 22F770820d darwin-arm64,
    locale en-FR)
    • Flutter version 3.13.1 on channel stable at
      /Users/renanyoy/code/sdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e1e47221e8 (6 days ago), 2023-08-22 21:43:18 -0700
    • Engine revision b20183e040
    • Dart version 3.1.0
    • DevTools version 2.25.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/renanyoy/Library/Android/sdk
    • Platform android-33, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14E300c
    • CocoaPods version 1.12.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2022.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-17.0.6b802.4-9586694)

[✓] VS Code (version 1.81.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.70.0

[✓] Connected device (3 available)
    • Pixel 6 (mobile) • 19291FDF60092F • android-arm64  • Android 13 (API 33)
    • macOS (desktop)  • macos          • darwin-arm64   • macOS 13.4.1 22F770820d darwin-arm64
    • Chrome (web)     • chrome         • web-javascript • Google Chrome 116.0.5845.110

[✓] Network resources
    • All expected network resources are available.

• No issues found!

```

# More environment information
flutter web

**Comment by spydon** [comment] 2023-08-29 07:20
And this works for you on other platforms?
I'm guessing you have overridden something in your game class or that your components are placed where you think that they are. You can set `debugMode = true` and you'll see where they are placed.

**Comment by renanyoy** [comment] 2023-08-30 05:33
it seems not better on android, my game widget

```
class DaGame extends Forge2DGame  /*with PanDetector*/ {
  final onChanged = Event<Component>();
  static final screenSize = Vector2(1200, 900);
  final fpsComponent = FpsComponent();
  final rect = RectangleComponent(
      position: Vector2(100, 100),
      size: Vector2(100, 100),
      paint: Paint()..color = const Color(0xFF00FF00));
  final frame = RectangleComponent(
      size: screenSize,
      paint: Paint()
        ..style = PaintingStyle.stroke
        ..strokeWidth = 2
        ..color = const Color(0xFF00FF00));
  DaGame()
      : super(
            zoom: 1,
            gravity: Vector2(0, 10),
            camera: Camera()
              ..viewport = FixedResolutionViewport(screenSize, clip: false));
  @override
  Future<void> onLoad() async {
    await super.onLoad();
    add(fpsComponent);
    add(frame);
    add(rect);
  }

  @override
  void onGameResize(Vector2 size) {
    Debug.info('onGameResize: $size');
    super.onGameResize(size);
  }

  double time = 0;
  @override
  void update(double dt) {
    super.update(dt);
    time += dt;
    rect.position = Vector2(100 + 200 * sin(time), 100);
  }

  @override
  void render(Canvas canvas) {
    super.render(canvas);
  }

  @override
  void onChildrenChanged(Component child, ChildrenChangeType type) {
    super.onChildrenChanged(child, type);
    onChanged.fire(child);
  }

  Vector2 camStart = Vector2.zero();
  Vector2 dragStart = Vector2.zero();
/*

  @override
  void onPanDown(DragDownInfo info) {
    Debug.info('panDown: ${info.eventPosition.game}');
    dragStart = info.eventPosition.game;
    camStart = camera.position.clone();
  }

  @override
  void onPanStart(DragStartInfo info) {
    Debug.info('panStart: ${info.eventPosition.game}');
  }

  @override
  void onPanUpdate(DragUpdateInfo info) {
    final delta = info.eventPosition.game - dragStart;
    Debug.info('panUpdate: $delta');
    final position = camStart - camera.viewport.scaleVector(delta);
    camera.snapTo(position);
  }

  @override
  void onPanEnd(DragEndInfo info) {
    Debug.info('panEnd: ${info.velocity}');
  }

  @override
  void onPanCancel() {
    Debug.info('panCancel');
  }
*/
  double get fps => fpsComponent.fps;
  @override
  bool get debugMode => false; //kDebugMode;
}

```

**Comment by spydon** [comment] 2023-08-30 06:33
Aaah, the problem is that you're using Forge2DGame, it has not yet been converted to the new camera system yet. It will be in a week or two.

**Comment by spydon** [comment] 2023-08-30 10:58
Closing in favor of #2547

**Closed by spydon** 2023-08-30 10:58 UTC
Labels: bug
