### ISSUE TITLE
Klondike's example freeze

### ISSUE THREAD

**Issue by shingo-nakanishi** [flame-engine/flame#3279] opened 2024-08-23 13:43 UTC
### What happened?

https://docs.flame-engine.org/latest/tutorials/klondike/step5.html

When playing, I often encounter a large number of errors like the ones in the attached image as I approach the final stages, causing the game to freeze. (So far, I haven't been able to clear the game because of these errors.)

<img width="638" alt="Screenshot 2024-08-23 at 22 25 13" src="https://github.com/user-attachments/assets/b7c411bd-df77-4111-b6c4-b0bd0e4c618f">

### What do you expect?

I hope it won't freeze.

### How can we reproduce this?

The method to reproduce this issue is unclear, but it has occurred under the following circumstances:

- Near the end of the game
- The moment the first card flips over after pressing the 'New deal' button"

### Affected platforms

Web

### Are you interested in working on a PR for this?

- [ ] I want to work on this

**Comment by spydon** [comment] 2024-08-23 13:51
I just tried playing it through and I had no errors at all, which browser and browser version are you on? Have you tried in inkognito mode with all plugins turned off?

**Comment by shingo-nakanishi** [comment] 2024-08-23 14:06
@spydon 

Thank you for trying it.

- Chrome: Version 128.0.6613.84 (Official Build) (arm64)
- All Extensions off.
- Not inkognito mode

**Comment by spydon** [comment] 2024-08-24 15:54
I just tried on exactly the same Chrome version and I can't reproduce it, try in inkognito mode, or make sure that your cache is clean. Or worst case, try on another computer.

I'll close this as not reproducible, but you can still comment on it if you find out what it was.

**Closed by spydon** 2024-08-24 15:54 UTC
Labels: bug
