### ISSUE TITLE
Frame drops when not touching the screen

### ISSUE THREAD

**Issue by Gericop** [flame-engine/flame#213] opened 2020-01-29 13:57 UTC
I have been working a game for some time now and noticed that the FPS drops significantly if the user is not touching the screen for a few seconds. (The real problem is the stuttering due to frame drops.)

Here are an empty (no visible objects on the screen) game's frame rendering times when the user is touching constantly the screen:
![kép](https://user-images.githubusercontent.com/5181621/73362179-a5176680-42a6-11ea-86d8-12dbe3e7503b.png)

And these are the results after a few seconds when nothing is touching the screen:
![kép](https://user-images.githubusercontent.com/5181621/73362481-371f6f00-42a7-11ea-84f8-215bc0401935.png)

I don't know if this is a limitation of Flutter or the method used to update the frames but it's really bad when the game moves at a rapid pace and the blocks have visible stuttering.

**Comment by luanpotter** [comment] 2020-01-29 15:59
Is there no other differences when the user taps the screen? Like do you handle the tap and do something that could cause the difference to happens?

Otherwise would be very hard to solve, probably something to do with some energy saving optimization on your hardware or something deep within Flutter engine.

**Comment by erickzanardo** [comment] 2020-01-29 17:42
another important thing to consider, is that, for some reason that fps overlay from flutter not always reflects the in game fps, I suggest you checking out the flame fps indicator, you can see an example [here](https://flame-engine.org/docs/debug.md)

**Comment by Gericop** [comment] 2020-01-29 17:56
@luanpotter The results you see above are from a blank `BaseGame` without any added components / handlers and it's the same if I add objects that move around the screen. I think the Flutter engine is trying to do some battery optimizations when the user is not interacting with the app, and I posted it here hoping you knew something about that.

@erickzanardo It's not really about the FPS, but the fast moving objects on the screen have visible stuttering and it's quite annoying...

**Comment by erickzanardo** [comment] 2020-01-29 18:55
oh, I see @Gericop , if it has visible effects, then my suggestion is worthless.

I have never saw that happening, but usually, the games I work on, has constant interactions, so that is probably the reason.

If I would guess, I would say that your assumption on the battery saving optimization is the reason, given that Flutter is meant for apps, and not specifically for games, it makes sense to slow down rendering to save battery. And if that is indeed the case, it is hard to think on what we could on the Flame to prevent that, as this may be a behaviour deep inside flutter. Neverthless, I think we should do some research and try to find if there is a way to prevent that behaviour, may there is an option to disable battery saving, or something like that.

Thanks for bringing this to our attention.

**Comment by ddonze** [comment] 2020-01-29 19:05
@Gericop what device is this? I have seen similar behavior on my iPhoneSE. It sporadically seems to drop frames and run at about 45fps instead of 60. It is rather unpredictable and I haven't been able to track it down. I have actually noticed similar behavior with a 100% native Obj-C app using a CADisplayLink as a timing mechanism (Flutter uses the same mechanism under the hood for VSync). Power-saving is a possibility, or it could be an internal issue with CADisplayLink. I would also like to point out that I am always in a debug build. I haven't tested this issue in a release build (in Flutter or Native). It's possible that debug mode is creating some extra tasks that get out of sync.

**Comment by ddonze** [comment] 2020-01-29 19:20
I seem to recall, years ago, there was an issue where screen orientation caused slow down. If you were using CADisplayLink, you basically had to disable auto-rotation or you would get slow-down. That was a loooooong time ago - like the iPhone 3GS. So I have a hard time believing it is still a problem.

**Comment by Gericop** [comment] 2020-01-30 00:51
@ddonze It's an HTC 10. It'd be nice to know whether it's a Flutter engine optimization thing or the device is trying to save battery by using less resources after a few seconds (this seems rather unlikely as it would be bad for the native 3D performance as well).

Anyways, while I was investigating where I could optimize the game, I found a pretty big problem with the `TextComponent` (technically more like `TextConfig`). Now it creates a new `TextPainter` object and calls `layout()` on it in _every frame_. This introduces both a garbage collection problem (creating new objects in frame render calls are bad anyways) and the re-measurement of the text which is a performance-heavy operation.

**Comment by luanpotter** [comment] 2020-01-30 13:44
@Gericop I believe it should be easy to fix, we can create the text painter only on the `_updateBox` method. Having it pre-calculated and just render on every frame. What do you think? I'd be glad to merge a PR for that.

**Comment by Gericop** [comment] 2020-01-30 13:53
Yeah, it's basically that. I've already fixed it for my game but I'll do a PR.

Also, would you be interested in including a `ScoreComponent` or something similar that pre-allocates the digits from 0-9 as `TextComponents` and renders the integers one by one? I know it's rather an edge case but I needed this in my game as the score is increasing continuously (10 times / sec initially and it grows linearly) and every increase (a change of text) means a new measurement of the text which is, yet again, sub-optimal.

**Comment by erickzanardo** [comment] 2020-01-30 14:02
@Gericop that ScoreComponent seems really cool, as you said it is really an Edge case, my suggestion would it be that you make it as a package, we have a section only for packages and plugins on [Awesome Flame](https://github.com/flame-engine/awesome-flame#plugins--libraries) and this would be a great addition.

**Comment by erickzanardo** [comment] 2020-02-29 18:24
Hey @Gericop any news on this?

Have you had time to work on that PR?

Since we discovered that the problem is on TextComponets, I am thinking on closing this and openning an specific PR for that. What do you people think?

**Comment by Gericop** [comment] 2020-02-29 23:22
@erickzanardo Yeah, sorry for the delay, I've been busy with work. I'll do a PR for the `TextComponent` on Monday, probably. Also, I've been thinking: does `TextBoxComponent` have the same issue?

**Comment by Gericop** [comment] 2020-03-03 18:06
@erickzanardo There's a PR (#226) now. Check it out when you have some time.

**Comment by erickzanardo** [comment] 2020-03-04 13:21
Awesome, thanks! Gonna take a look on it as soon as possible.

**Comment by erickzanardo** [comment] 2020-03-05 13:27
Closing this since the PR has already be merged.

**Closed by erickzanardo** 2020-03-05 13:27 UTC
Labels: enhancement, help wanted
