### ISSUE TITLE
RectangleComponent does not re-render paint after construction

### ISSUE THREAD

**Issue by lukepighetti** [flame-engine/flame#2166] opened 2022-11-13 13:42 UTC
# Current bug behavior
RectangleComponent doesn't re-render paint after construction

# Expected behavior
RectangleComponent does re-render paint after construction

# Steps to reproduce

<img width="595" alt="Screen Shot 2022-11-13 at 8 48 43 AM" src="https://user-images.githubusercontent.com/666539/201525148-41eaa248-9673-4fc3-b5e0-b26730da925d.png">

```dart
class MyGame extends FlameGame {
  final rectangle = MyRectangle();

  @override
  Future<void>? onLoad() async {
    add(rectangle);
  }
}

class MyRectangle extends RectangleComponent {
  MyRectangle() : super(size: Vector2(50, 50));

  @override
  Future<void> onLoad() async {
    size = Vector2(150, 150); // this size change doesn't re-render paint

    debugMode = true;
    position = Vector2(150, 150);
    paint = Paint()..color = Colors.green;
  }
}
```

# Flutter doctor output

```
[✓] Flutter (Channel stable, 3.3.7, on macOS 12.6 21G115 darwin-arm, locale en-US)
    • Flutter version 3.3.7 on channel stable at /Users/lukepighetti/development/flutter/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision e99c9c7cd9 (12 days ago), 2022-11-01 16:59:00 -0700
    • Engine revision 857bd6b74c
    • Dart version 2.18.4
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/lukepighetti/Library/Android/sdk
    • Platform android-32, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14B47b
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.73.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.52.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 107.0.5304.110

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!

```

# More environment information

* Flame version: 1.4.0
* Platform affected: web, perhaps more

# Log information

```
Enter log information in this code block
```

# More information

**Comment by ufrshubham** [comment] 2022-11-13 13:44
Possible duplicate of #1545. At least root cause seems to be the same. @lukepighetti please set the size while construction of your component to get passed this.

**Comment by lukepighetti** [comment] 2022-11-13 13:50
Updated the original issue to reflect this, thank you

**Closed** 2022-11-22 21:10 UTC
Labels: bug
