### ISSUE TITLE
When you touch the screen for the first time, the picture will be stuck a little time

### ISSUE THREAD

**Issue by itwangyu** [flame-engine/flame#763] opened 2021-04-15 03:35 UTC
# Current bug behaviour
Open the app, touch the screen, the screen will jam. There will also be a jam without setting any touch callback

# Expected behaviour
No catons

# Steps to reproduce
see this demo,you can find this issue
https://github.com/itwangyu/boxgame.git   the code is on branch : master

Open the app and click on the screen, the fly will get stuck. After that, you can't get stuck at any point

Back quit the app, click again, and the fly will get stuck again. I want to know what the problem is

```
import 'dart:math';

import 'package:flame/flame.dart';
import 'package:flame/game.dart';
import 'package:flutter/material.dart';
import 'package:flame/util.dart';
import 'package:flutter/services.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Util flameUtil = Util();
  await flameUtil.fullScreen();
  await flameUtil.setOrientation(DeviceOrientation.portraitUp);

  ///点击方块下落游戏
  final game = BoxGame();

  // TapGestureRecognizer tapper = TapGestureRecognizer();
  // tapper.onTapDown = game.onTapDown;
  // flameUtil.addGestureRecognizer(tapper);

  runApp(game.widget);
}

class BoxGame extends Game {
  Random mRandom = Random();
  bool hasInit = false;

  //屏幕尺寸
  Size mScreenSize;

  //一个苍蝇的尺寸，也是单位宽度，以后的尺寸计算都基于这个单位。无论屏幕多宽，都能并排放置9个苍蝇
  double tileSize;

  Rect rect;
  Paint paint;

  BoxGame() {
    initialize();
  }

  void initialize() async {
    resize(await Flame.util.initialDimensions());
    rect = Rect.fromLTWH(0, 0, tileSize, tileSize);
    paint = Paint();
    paint.color = Colors.blue;

    hasInit = true;
  }

  @override
  void resize(Size size) {
    super.resize(size);
    mScreenSize = size;
    //设定的单位尺寸是宽度的九分之一，也就是将屏幕宽度分为九个区块
    tileSize = mScreenSize.width / 9;
  }

  @override
  void render(Canvas canvas) {
    if (!hasInit) {
      return;
    }
    canvas.drawRect(rect, paint);
  }

  @override
  void update(double t) {
    if (!hasInit) {
      return;
    }
    rect = rect.translate(0, tileSize * 6 * t);
  }
}

```

The above is a simplified version of the code that can reproduce Caton. When you run the game, there will be a box falling down. When you click anywhere on the screen for the first time, the box will get stuck for a moment and drop the frame. This button is limited to the first click on the screen. Exit the app, come in again, and then click the screen to reappear Caton again.

The flash version I used is 0.29.4, which has nothing to do with mobile phones. I tried many mobile phones and they all got stuck.

# Flutter doctor output
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19041.868], locale zh-CN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] Connected device (3 available)

• No issues found!

```
Output of: flutter doctor -v

$ flutter doctor -v
[√] Flutter (Channel stable, 2.0.4, on Microsoft Windows [Version 10.0.19041.868], locale zh-CN)
    • Flutter version 2.0.4 at E:\flutterSdk\flutter
    • Framework revision b1395592de (13 days ago), 2021-04-01 14:25:01 -0700
    • Engine revision 2dce47073a
    • Dart version 2.12.2
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at E:\sdk
    • Platform android-S, build-tools 30.0.2
    • ANDROID_HOME = E:\sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (3 available)
    • Redmi Note 8 Pro (mobile) • au4hssnruwozypdq • android-arm64  • Android 9 (API 28)
    • Chrome (web)              • chrome           • web-javascript • Google Chrome 88.0.4324.150
    • Edge (web)                • edge             • web-javascript • Microsoft Edge 89.0.774.76

• No issues found!

```

# More environment information

# Log information

```
Enter log information in this code block
```

# More information

**Comment by itwangyu** [comment] 2021-04-15 03:37
https://github.com/itwangyu/boxgame.git  branch：master

**Comment by spydon** [comment] 2021-04-15 07:33
Hi, please only use English when creating an issue.
There is not code in your example repository, only an empty readme file.

**Comment by itwangyu** [comment] 2021-04-15 08:09
> Hi, please only use English when creating an issue.
> There is not code in your example repository, only an empty readme file.

the code is on the branch master.
my issue:
when i enter the game and tap the screen for the first time ,the animation will be struck about 0.5 second.
then , touch back and quit the game .  open game again , tap the screen ,it will be struck a little time again.

**Comment by erickzanardo** [comment] 2021-04-15 12:58
@itwangyu please, update your issue description to be all in english with the info you sent on these last comments. It makes easier for other users and team member to ready the issue as the description is the first thing we look.

About your problem, I took a quick scan on the code you shared. my first bet would be that it is just some assets taking some time to load, but it is hard to be 100% as the repository you linked has a fair amount of code.

It would be good if you could isolate this problem into a minimal reproducible code, which uses the latest version of Flame, be is 0.29.4 ou 1.0.0-rc9. Because otherwise it will be difficult for us to investigate due to this be happening on project with a lot of things going on.

**Comment by itwangyu** [comment] 2021-04-17 07:14
> @itwangyu please, update your issue description to be all in english with the info you sent on these last comments. It makes easier for other users and team members to read the issue as the description is the first thing we look.
> 
> About your problem, I took a quick scan on the code you shared. my first bet would be that it is just some assets taking some time to load, but it is hard to be 100% as the repository you linked has a fair amount of code.
> 
> It would be good if you could isolate this problem into a minimal reproducible code, which uses the latest version of Flame, be is 0.29.4 or 1.0.0-rc9. Because otherwise it will be difficult for us to investigate due to this be happening on project with a lot of things going on.

I've updated the problem description with code that I can run directly

**Comment by itwangyu** [comment] 2021-04-17 07:14
> Hi, please only use English when creating an issue.
> There is not code in your example repository, only an empty readme file.

I've updated the problem description with code that I can run directly

**Comment by luanpotter** [comment] 2021-06-01 01:59
@itwangyu in the shared example, there is no tap detector or handler bound whatsoever, so I can't see how that could be an issue with flame... normally I would imagine the issue is you need to pre-load images and assets. in your simplified example, I can see you have:

```
  BoxGame() {
    initialize();
  }

  void initialize() async {
    resize(await Flame.util.initialDimensions());
    rect = Rect.fromLTWH(0, 0, tileSize, tileSize);
    paint = Paint();
    paint.color = Colors.blue;

    hasInit = true;
  }
```

which is not the best way to initialize your game. if you use the `onLoad` function with proper `await`s as needed, that might be a better strategy. however even with the code as is, I don't see how tapping could be related to anything. if the problem was unrelated to tapping I would bet it had to do with your `hasInit` control variable.

**Comment by erickzanardo** [comment] 2021-06-22 00:46
As @luanpotter pointed it out, this doesn't seems to be an issue with Flame itself. Please try the suggestions pointed by him.

I am closing this, but feel free to add more comments here if you still have doubts and if you found additional evidences that this is indeed a bug, let us know and we can re open the issue.

Thanks.

**Closed by erickzanardo** 2021-06-22 00:46 UTC
Labels: bug
