### ISSUE TITLE
`ImageComposition` results in black image

### ISSUE THREAD

**Issue by spydon** [flame-engine/flame#1698] opened 2022-06-04 09:35 UTC
# Current bug behaviour
When using the `ImageComposition` in Flutter 3.0.1 it results in a black image, but seemingly not in 2.10.0 (Pasha tried that).

# Expected behaviour
The actual composition of the images in the resulting image object.

# Steps to reproduce
```dart
class MyGame extends FlameGame {
  static const imagePath = 'profile.jpg';

  @override
  Future<void> onLoad() async {
    super.onLoad();
    final image = await images.load(imagePath);

    add(SpriteComponent.fromImage(
      image,
      position: Vector2(0, 0),
      size: Vector2(100, 100),
    )..debugMode = true);

    final compositionImage =
        await (ImageComposition()
              ..add(image, Vector2.zero()))
            .compose();

    add(SpriteComponent.fromImage(
      compositionImage,
      position: Vector2(100, 0),
      size: Vector2(100, 100),
    )..debugMode = true);
  }
}
```

I've tried with both jpg and png.

# Flutter doctor output

```
[✓] Flutter (Channel stable, 3.0.1, on Arch Linux 5.18.0-arch1-1, locale en_DK.UTF-8)
    • Flutter version 3.0.1 at /home/spydon/bin/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision fb57da5f94 (2 weeks ago), 2022-05-19 15:50:29 -0700
    • Engine revision caaafc5604
    • Dart version 2.17.1
    • DevTools version 2.12.2

```

# More environment information

* Flame version: `main`
* Platform affected: linux, web (are the ones I've tried, Windows might work according to Discord)

# Log information

```
Enter log information in this code block
```

# More information

**Comment by st-pasha** [comment] 2022-06-11 15:59
I believe the root cause here is the Flutter bug https://github.com/flutter/flutter/issues/103803

**Comment by spydon** [comment] 2022-10-21 17:18
It's now fixed in Flutter beta.

**Comment by wolfenrain** [comment] 2023-09-21 11:34
Closing this as it has long been resolved in later Flutter versions.

**Closed by wolfenrain** 2023-09-21 11:34 UTC
Labels: Flutter issue
