### ISSUE TITLE
add liquid simulation

### ISSUE THREAD

**Issue by iBinbro** [flame-engine/flame#2942] opened 2023-12-21 04:15 UTC
I am learning forge2d recently, box2d is really shocking, LiquidFun is also developed from box2d, it would be great if LiquidFun can also be integrated.

**Comment by spydon** [comment] 2023-12-21 06:22
Duplicate of https://github.com/flame-engine/forge2d/issues/8

**Closed by spydon** 2023-12-21 06:22 UTC
Labels: enhancement

**Comment by iBinbro** [comment] 2023-12-21 08:16
> Duplicate of [flame-engine/forge2d#8](https://github.com/flame-engine/forge2d/issues/8)

I found that the particle system of forge2d seems to be used to achieve fluid effects, but I have not seen any examples of the particle system of forge2d being used in flame. My abilities are limited. I tried using forge2d particles, but I didn’t see any effect.

**Comment by spydon** [comment] 2023-12-21 09:50
There is no rendering built in for particles in flame_forge2d, so you have to handle the rendering of the particles yourself (Forge2D only handles their size and position). You can see an example of how it is done outside of Flutter and Flame here:
https://github.com/flame-engine/forge2d/blob/main/packages/forge2d/example/web/particles.dart
